name: receitaws
description: Client for Receita WS API
version: 1.0.0
repository: https://github.com/funccloud/receitaws

environment:
  sdk: ^3.5.0

# Add regular dependencies here.
dependencies:
  http: ^1.2.2

dev_dependencies:
  lints: ^4.0.0
  test: ^1.24.0

