name: receitaws_api
description: Client for Receita WS API
version: 1.1.0
repository: https://github.com/funccloud/receitaws

environment:
  sdk: ^3.8.0

dependencies:
  http: ^1.6.0

dev_dependencies:
  lints: ^6.1.0
  test: ^1.25.0
